### ISSUE TITLE
(B): Создать End-point'ы для списка ревью

### ISSUE THREAD

**Issue by valsaven** [maximumtest/360#17]
Подгрузка данных отдельно для каждого экрана: список ревью, список пользователей в ревью, сами отзывы внутри пользователя.

Это поможет решить проблему просмотра отзывов по одному человеку с переключением даты в таймлайне (типа ретроспективно посмотреть тренд)

Драфт схемы данных, которую обсуждали на первых встречах:

![review-erm](https://user-images.githubusercontent.com/2467385/52624383-af86f780-2ebf-11e9-982d-3a1752c6a184.png)

**Comment by MooGeek** [comment]
Подгрузка данных отдельно для каждого экрана: список ревью, список пользователей в ревью, сами отзывы внутри пользователя.

Это поможет решить проблему просмотра отзывов по одному человеку с переключением даты в таймлайне (типа ретроспективно посмотреть тренд)

**Comment by MooGeek** [comment]
Драфт схемы данных, которую обсуждали на первых встречах:

![review-erm](https://user-images.githubusercontent.com/2467385/52624383-af86f780-2ebf-11e9-982d-3a1752c6a184.png)
