### ISSUE TITLE
(F): Создать компонент Timeline

### ISSUE THREAD

**Issue by valsaven** [maximumtest/360#19]
Можно, для начала, взять просто базовый дэйтпикер, например, а потом ближе к делу понять как его затюнить

**Comment by MooGeek** [comment]
Можно, для начала, взять просто базовый дэйтпикер, например, а потом ближе к делу понять как его затюнить

**Comment by MooGeek** [comment]
Закрыто из-за неактуальности: решили делать менее атомарные ишки
