### ISSUE TITLE
(F): Создать карточки Ревью, Юзер, Отзыв

### ISSUE THREAD

**Issue by valsaven** [maximumtest/360#21]
- [ ] Ревью
- [ ] Юзер
- [ ] Отзыв

**Отзыв:**

1. Ревьюер (имя, например)
2. Объект тела отзыва с подобной структурой: {type: 'text', body: 'lol kiek otziv'} (для начала просто текст, засчет хранения объектом получим возможность без геморроя расширить)

**Юзер:**

1. Аватарка
2. Имя
3. Комментарий (для начала просто текст; можно указать должность, например)

**Ревью:**

1. Название
2. Описание

**Comment by MooGeek** [comment]
**Отзыв:**

1. Ревьюер (имя, например)
2. Объект тела отзыва с подобной структурой: {type: 'text', body: 'lol kiek otziv'} (для начала просто текст, засчет хранения объектом получим возможность без геморроя расширить)

**Юзер:**

1. Аватарка
2. Имя
3. Комментарий (для начала просто текст; можно указать должность, например)

**Ревью:**

1. Название
2. Описание

**Comment by MooGeek** [comment]
Закрыто из-за неактуальности: решили делать менее атомарные ишки
