### ISSUE TITLE
(B): Создать End-point для авторизации

### ISSUE THREAD

**Issue by valsaven** [maximumtest/360#22]

**Comment by MooGeek** [comment]
Тут @evgeniakuzina может описать. Я ж правильно понимаю, что оно уже все есть?

**Comment by evgeniakuzina** [comment]
@MooGeek @valsaven все верно, в мр это добавила. https://github.com/maximumtest/360/pull/15. Постараюсь сегодня допилить штуку с кодами для верификации имейла и восстановления пароля. Но в целом уже можно ориентироваться на роуты в api.php.
