### ISSUE TITLE
(B): хранение шаблонов (анкет)

### ISSUE THREAD

**Issue by MooGeek** [maximumtest/360#46]
Шаблон - список вопросов разного типа. Грубо говоря:

```json
{  
   "name": "template #1",
   "items": [  
      {  
         "type": "radio",
         "items": [...]
      },
      {  
         "type": "text"
      },
      ...
   ]
}
```

Соответственно, нужно сделать API (CRUD)

**Comment by MooGeek** [comment]
![image](https://user-images.githubusercontent.com/2467385/55328697-9f3dd280-5495-11e9-9848-f8af7d4d0a23.png)

**Comment by lo2s** [comment]
Реализовано: #49
