### ISSUE TITLE
(B): Похвала (kudos)

### ISSUE THREAD

**Issue by MooGeek** [maximumtest/360#50]
Сущность "похвалы". Решили разделить их на предсозданные категории, типа "Технические навыки", "Личные качества", "Социальные" и т.п.

Опционально можно добавить к похвале тэг(и) и написать текстовый комментарий.

В будущем можно выводить историю всех аналогичных событий для пользователя или всех пользователей в системе.

**Comment by lo2s** [comment]
Реализовано #64
